env:
  matrix:
    - FEDORA='f26'	TESTING=''
    - FEDORA='f26'	TESTING='-testing'
    - FEDORA='f27'	TESTING=''
    - FEDORA='f27'	TESTING='-testing'
    - FEDORA='f28'	TESTING=''
    - FEDORA='f28'	TESTING='-testing'
    - FEDORA='f29'	TESTING=''
    - FEDORA='f29'	TESTING='-testing'
    - FEDORA='f30'	TESTING=''
    - FEDORA='f30'	TESTING='-testing'
    - FEDORA='f31'	TESTING=''
    - FEDORA='f31'	TESTING='-testing'
    - FEDORA='f32'	TESTING=''
    - FEDORA='f32'	TESTING='-testing'


install:
 - docker build -f "Dockerfile.$FEDORA$TESTING" -t "test-$FEDORA$TESTING" .


script:
 - docker run -it --rm -v $PWD:/src "test-$FEDORA$TESTING" make -C '/src/asf/sam0/applications/led_toggle/samd21_xplained_pro/gcc'


services:
 - docker

