FROM	fedora:32

RUN	dnf install -y				\
		arm-none-eabi-gcc-cs		\
		arm-none-eabi-gcc-cs-c++	\
		arm-none-eabi-newlib		\
		make

RUN	dnf upgrade -y --enablerepo=updates-testing	\
		arm-none-eabi-gcc-cs			\
		arm-none-eabi-gcc-cs-c++		\
		arm-none-eabi-newlib

