FROM	fedora:31

# Testing arm-none-eabi-newlib from Koji
RUN	curl --output '/tmp/arm-none-eabi-newlib-3.1.0-4.fc31.noarch.rpm' 'https://kojipkgs.fedoraproject.org//packages/arm-none-eabi-newlib/3.1.0/4.fc31/noarch/arm-none-eabi-newlib-3.1.0-4.fc31.noarch.rpm'
RUN	rpm --install '/tmp/arm-none-eabi-newlib-3.1.0-4.fc31.noarch.rpm'

RUN	dnf install -y				\
		arm-none-eabi-gcc-cs		\
		arm-none-eabi-gcc-cs-c++	\
		make

